# Generated by Django 4.1 on 2023-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0005_alter_character_alignment_alter_character_background_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('name', 'character_class', 'race', 'player_name'), name='unique_character'),
        ),
    ]
