# Generated by Django 4.1 on 2023-08-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0009_character_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Speed'),
        ),
    ]
