# Generated by Django 4.1 on 2023-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0002_character_delete_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alignment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Armor Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_hit_points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Current Hit Points'),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Experience Points'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Hit Dice'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_dice_total',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Hit Dice Total'),
        ),
        migrations.AlterField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Initiative'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Character Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Players Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='temporary_hit_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Temporary Hit Points'),
        ),
        migrations.AlterField(
            model_name='character',
            name='total_hit_points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Total Hit Points'),
        ),
    ]
