# Generated by Django 4.1 on 2023-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0003_alter_character_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Alignment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_dice',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Hit Dice'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_dice_total',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Hit Dice Total'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Character Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Players Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(default='', max_length=20, verbose_name='Race'),
        ),
    ]
