# Generated by Django 4.1 on 2023-08-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0006_character_unique_character'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='unique_character',
        ),
    ]
