# Generated by Django 4.1 on 2023-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0007_remove_character_unique_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='acrobatics',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Acrobatics Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='animal_handling',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Animal Handling Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='arcana',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Arcana Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='athletics',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Athletics Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Charisma Score'),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Constitution Score'),
        ),
        migrations.AddField(
            model_name='character',
            name='deception',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Deception Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Dexterity Score'),
        ),
        migrations.AddField(
            model_name='character',
            name='history',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Distory Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='insight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Insight Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='inspiration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inspiration'),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Intelligence Score'),
        ),
        migrations.AddField(
            model_name='character',
            name='intimidation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Intimidation Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='investigation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Investigation Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='medicine',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Medicine Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='nature',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mature Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='perception',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Perception Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='performance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Performance Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='persuasion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Persuasion Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiency',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Proficiency Bonus'),
        ),
        migrations.AddField(
            model_name='character',
            name='religion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Religion Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw_charisma',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Charisma Saving Throw'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw_constitution',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Constitution Saving Throw'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw_dexterity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dexterity Saving Throw'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw_intelligence',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Intelligence Saving Throw'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw_strength',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Strength Saving Throw'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw_wisdom',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Wisdom Saving Throw'),
        ),
        migrations.AddField(
            model_name='character',
            name='sleight_of_hand',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sleight of Hand Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='stealth',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stealth Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Strength Score'),
        ),
        migrations.AddField(
            model_name='character',
            name='survival',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Survival Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Wisdom Score'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Armor Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(default=30, verbose_name='Speed'),
        ),
    ]
