# Generated by Django 4.1 on 2023-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0008_character_acrobatics_character_animal_handling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.JSONField(null=True),
        ),
    ]
