# Generated by Django 4.1 on 2023-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0010_alter_character_level_alter_character_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('spell_id', models.IntegerField(primary_key=True, serialize=False)),
                ('spell_name', models.CharField(max_length=50)),
                ('spell_level', models.IntegerField(blank=True, default=0, null=True)),
                ('spell_type', models.CharField(blank=True, max_length=50, null=True)),
                ('casting_time', models.CharField(blank=True, max_length=50, null=True)),
                ('spell_range', models.CharField(blank=True, max_length=50, null=True)),
                ('components', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('higher_levels', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapons',
        ),
    ]
