# Generated by Django 4.1 on 2023-08-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0012_character_weapons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spells',
            new_name='Spell',
        ),
    ]
