# Generated by Django 4.1 on 2023-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0013_rename_spells_spell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weapon_type', models.CharField(max_length=10)),
                ('damage_dice', models.CharField(max_length=10)),
                ('damage_type', models.CharField(max_length=20)),
                ('range', models.CharField(max_length=10)),
                ('ammunition', models.BooleanField()),
                ('finesse', models.BooleanField()),
                ('heavy', models.BooleanField()),
                ('light', models.BooleanField()),
                ('loading', models.BooleanField()),
                ('reach', models.BooleanField()),
                ('special', models.BooleanField()),
                ('thrown', models.BooleanField()),
                ('two_handed', models.BooleanField()),
                ('versatile', models.BooleanField()),
                ('monk', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
