# Generated by Django 4.1 on 2023-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0014_weapon_character_spells_alter_character_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammunition',
            field=models.BooleanField(verbose_name='Ammunition'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_dice',
            field=models.CharField(max_length=10, verbose_name='Damage dice'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_type',
            field=models.CharField(max_length=20, verbose_name='Damage type'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='finesse',
            field=models.BooleanField(verbose_name='Finesse'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='heavy',
            field=models.BooleanField(verbose_name='Heavy'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='light',
            field=models.BooleanField(verbose_name='Light'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='loading',
            field=models.BooleanField(verbose_name='Loading'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='monk',
            field=models.BooleanField(verbose_name='Monk'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.CharField(max_length=10, verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reach',
            field=models.BooleanField(verbose_name='Reach'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='special',
            field=models.BooleanField(verbose_name='Special'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='thrown',
            field=models.BooleanField(verbose_name='Thrown'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='two_handed',
            field=models.BooleanField(verbose_name='Two handed'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='versatile',
            field=models.BooleanField(verbose_name='Versatile'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(max_length=10, verbose_name='Weapon type'),
        ),
    ]
