# Generated by Django 4.1 on 2023-09-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0015_weapon_weight_alter_weapon_ammunition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cost'),
        ),
    ]
