# Generated by Django 4.1 on 2023-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0016_weapon_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Cost'),
        ),
    ]
