# Generated by Django 4.1 on 2023-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0017_alter_weapon_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Range'),
        ),
    ]
