# Generated by Django 4.1 on 2023-09-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0019_alter_weapon_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spell_attack_bonus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Spell Attack Bonus Modifier'),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_save_dc',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Spell Save DC'),
        ),
    ]
