# Generated by Django 4.1 on 2023-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0020_character_spell_attack_bonus_character_spell_save_dc'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spellcasting_ability',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Spellcasting Ability'),
        ),
    ]
