# Generated by Django 4.1 on 2023-09-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0021_character_spellcasting_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='spells',
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, to='charloader.spell'),
        ),
    ]
