# Generated by Django 4.1 on 2023-09-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0022_remove_character_spells_character_spells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('class_specific', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
