# Generated by Django 4.1 on 2023-10-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0023_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
