# Generated by Django 4.1 on 2023-10-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charloader', '0025_alter_ability_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Name'),
        ),
    ]
